package com.kcs.starter.exceptions.base;

public enum ErrorCode {
    E_SERVER_ERROR, E_SERVER_ERROR_1, E_SERVER_ERROR_2, E_SERVER_ERROR_3, E_SERVER_ERROR_4, E_SERVER_ERROR_5,
    E_SERVER_ERROR_6, E_SERVER_ERROR_7, E_SERVER_ERROR_8, E_SERVER_ERROR_9
}
